version: 2

sources:
  - name: datastudio1
    tables:
      - name: email_clicks_ao_20220330
        description: >
            This source table is actually a set of files in external storage.
            The dbt-external-tables package provides handy macros for getting
            those files queryable, just in time for modeling.
                            
        external:
          location: s3://datastudio1/email_clicks_ao_20220330.csv
          

        # Specify ALL column names + datatypes.
        # Column order must match for CSVs, column names must match for other formats.
        # Some databases support schema inference.

        columns:
          - name: "Recipient E-mail"
            data_type: varchar(255)
            description: "Email"
          - name: "Action"
            data_type: varchar(255)
            description: "Action"
          - name: "Action Day"
            data_type: varchar(255)
            description: "Action Day"
          - name: "Action Time"
            data_type: varchar(255)
            description: "Action Time"
          - name: "Message ID"
            data_type: varchar(255)
            description: "Message ID"
          - name: "Subject"
            data_type: varchar(255)
            description: "Message Subject"
          - name: "Message Title"
            data_type: varchar(255)
            description: "Message Title"
          - name: "Automated Program Name"
            data_type: varchar(255)
            description: "AP Name"
          - name: "Campaign Name"
            data_type: varchar(255)
            description: "Campaign Name"
          - name: "Clicked URL"
            data_type: varchar(255)
            description: "Clicked URL"