version: 2

sources:
  - name: salesforce
    tables:
      - name: account
      - name: act_on_instance_c
      - name: act_on_instance_user_c
      - name: campaign_influence
      - name: campaign_member
      - name: campaign
      - name: contact_history
      - name: contact
      - name: contract
      - name: lead_history
      - name: lead
      - name: opportunity
      - name: opportunity_field_history
      - name: opportunity_line_item
      - name: product_2
      - name: task
      - name: user
  - name: data_studio_s3
    tables:
      - name: data_studio_emails
      - name: data_studio_forms
      - name: data_studio_landingpages
      - name: data_studio_media
      - name: data_studio_webinars
      - name: data_studio_webpages